name: Build

on:
  push:
    branches:
      - Master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DATA_HOST_IPS }}
          username: root
          key: ${{ secrets.DATASERVER_GITHUB_SSH }}
          script: |
            bash cd /var/www/dataserver && ./server_deploy.sh